### ISSUE TITLE
DW3 bugs

### ISSUE THREAD

**Issue by gameboy9** [gameboy9/DW3Randomizer#1]
Hero can still learn Outside twice.
Spells should be learned in a "top to bottom" order.  Otherwise, the spells act in a weird way if they start to be learned on page 2 or 3...

Bug finding credit:  deranged_squirrel_fighter

**Comment by gameboy9** [comment]
Hero no longer learns Outside twice.  (0.10.2)

The second issue is still outstanding...

**Comment by Reiska42** [comment]
If the coffin under the pyramid has an item other than the Golden Claw, you can open it infinitely.

**Comment by Reiska42** [comment]
When a random enemy uses Zoma's disruptive wave freeze beam thing, it still says Zoma's using it (seems his name's hardcoded in the attack message).

**Comment by gameboy9** [comment]
I'll have to look at the first one, Reiska... I may just have to put it back to the Golden Claw, or just make it empty.

The second one is far worse than you describe... if the disruptive wave hits while other monsters are dead, it actually revives them without seeing their image.  Weird!  And also not cool.  So that enemy technique will have to be removed from the randomizer.  Except Zoma, of course.

**Comment by Reiska42** [comment]
Interesting, I hadn't noticed that!

As an incidental note, the chests on the top floor of the pyramid with fixed encounters _do_ work and still spawn the fixed encounter (for me, it was always 4 Shadows), so that's good.  

I still have myself a good laugh when I see some crazy low-level monster pull out something unexpectedly deadly - I got Black Ravens in a run last night which could cast Explodet and use Zoma's blizzard breath.  Died a lot to those. XD  Also had something cast Sacrifice but I forget what.

The best part of that seed though to me is the Iron Claw which can be USEd to do over 100 damage to all enemies, and Firebal hitting for like 90 damage. XD

**Comment by gameboy9** [comment]
The Golden Claw issue is fixed, and the fight spells are now being learned from the top down.  For some reason, that's not happening with the command spells, but that's only a very minor graphical issue, so I'm going to close this issue.

The freezing waves issue was resolved in a previous version I believe.
